-- Migration: Update current_plan constraint to remove plan-100
-- This migration updates the CHECK constraint on current_plan column
-- to only allow: 'plan-10' (Basic/Free), 'plan-20' (Plus), 'plan-50' (Pro)

-- Drop the existing constraint if it exists
-- Note: The constraint name might vary, so we'll try common names
DO $$ 
BEGIN
    -- Try to drop constraint with common auto-generated names
    ALTER TABLE public.user_credits 
    DROP CONSTRAINT IF EXISTS user_credits_current_plan_check;
    
    -- Also try the constraint name that might be generated by Supabase
    ALTER TABLE public.user_credits 
    DROP CONSTRAINT IF EXISTS user_credits_current_plan_fkey;
END $$;

-- Add the updated constraint with only the allowed plans
ALTER TABLE public.user_credits
ADD CONSTRAINT user_credits_current_plan_check 
CHECK (current_plan IN ('plan-10', 'plan-20', 'plan-50'));

-- Optional: Update any existing records that might have 'plan-100' to NULL
-- (Uncomment the line below if you want to clear plan-100 values)
-- UPDATE public.user_credits SET current_plan = NULL WHERE current_plan = 'plan-100';

